<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Phoenix_Ipayment
 * @copyright  Copyright (c) 2009 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 */

$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_owner"><?php echo $this->__('Account holder') ?> <span class="required">*</span></label><br />
                <input type="text" title="<?php echo $this->__('Account holder') ?>" class="validate-ipayment-elv-owner required-entry input-text" id="<?php echo $_code ?>_owner" name="payment[owner]" value="<?php echo $this->htmlEscape($this->getInfoData('echeck_account_name')) ?>" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_name"><?php echo $this->__('Bank name') ?> <span class="required">*</span></label><br />
                <input type="text" id="<?php echo $_code ?>_bank_name" name="payment[bank_name]" title="<?php echo $this->__('Bank name') ?>" class="validate-ipayment-elv-bank-name required-entry input-text" value="" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_code"><?php echo $this->__('Bank code') ?> <span class="required">*</span></label><br />
                <input type="text" id="<?php echo $_code ?>_bank_code" name="payment[bank_code]" title="<?php echo $this->__('Bank code') ?>" class="validate-ipayment-elv-bank-code required-entry input-text" value="" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_account_number"><?php echo $this->__('Account number') ?> <span class="required">*</span></label><br />
                <input type="text" id="<?php echo $_code ?>_account_number" name="payment[account_number]" title="<?php echo $this->__('Account number') ?>" class="validate-ipayment-elv-account-number required-entry input-text" value="" autocomplete="off" />
            </div>
            <input type="hidden" id="<?php echo $_code ?>_bank_country" name="<?php echo $_code ?>_bank_country" value="<?php echo $this->getBankCountry() ?>" />
        	<input type="hidden" name="payment[additional_data]" value="" />
            <input type="hidden" id="ipayment_elv_request_status" value="" />
        </li>
    </ul>
</fieldset>
<div>
<span id="ipayment-elv-please-wait" style="display:none;" class="opc-please-wait">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/> &nbsp; <?php echo $this->__('Submitting payment information...') ?> &nbsp;
</span>
</div>

