<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Phoenix_Ipayment
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 */
?>
<b><?php echo Mage::helper('phoenix_ipayment')->__('You will be redirected to your bank server in a few seconds.'); ?></b>
<?php echo $this->getFormHtml() ?>
<script type="text/javascript">
//<![CDATA[
    window.onload = document.payauthForm.submit();
//]]>
</script>
